using Facet.Search.Generators.Models;
using System.Text;

namespace Facet.Search.Generators;

/// <summary>
/// Generates facet aggregation methods.
/// </summary>
internal static class AggregationGenerator
{
    public static string Generate(SearchableModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Search;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Aggregated facet results for {model.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public class {model.ClassName}FacetResults");
        sb.AppendLine("{");

        foreach (var facet in model.Facets)
        {
            if (facet.FacetType is "Categorical" or "Hierarchical")
                sb.AppendLine($"    public Dictionary<string, int> {facet.PropertyName} {{ get; set; }} = new();");
            else if (facet.FacetType == "Range")
            {
                sb.AppendLine($"    public {facet.PropertyType}? {facet.PropertyName}Min {{ get; set; }}");
                sb.AppendLine($"    public {facet.PropertyType}? {facet.PropertyName}Max {{ get; set; }}");
            }
            else if (facet.FacetType == "Boolean")
            {
                sb.AppendLine($"    public int {facet.PropertyName}TrueCount {{ get; set; }}");
                sb.AppendLine($"    public int {facet.PropertyName}FalseCount {{ get; set; }}");
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.ClassName}FacetAggregationExtensions");
        sb.AppendLine("{");

        GenerateAggregationMethod(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateAggregationMethod(StringBuilder sb, SearchableModel model)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Gets facet aggregations for {model.ClassName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static {model.ClassName}FacetResults GetFacetAggregations(");
        sb.AppendLine($"        this System.Linq.IQueryable<{model.Namespace}.{model.ClassName}> query)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var results = new {model.ClassName}FacetResults();");
        sb.AppendLine();

        foreach (var facet in model.Facets)
        {
            if (facet.FacetType is "Categorical" or "Hierarchical")
            {
                bool isNullable = facet.PropertyType.EndsWith("?") || facet.PropertyType == "string";
                sb.AppendLine($"        results.{facet.PropertyName} = query");
                if (isNullable)
                {
                    sb.AppendLine($"            .Where(x => x.{facet.PropertyName} != null)");
                    sb.AppendLine($"            .GroupBy(x => x.{facet.PropertyName}!)");
                }
                else
                {
                    sb.AppendLine($"            .GroupBy(x => x.{facet.PropertyName})");
                }
                sb.AppendLine("            .Select(g => new { Value = g.Key, Count = g.Count() })");

                if (facet.Limit > 0)
                {
                    var orderBy = facet.OrderBy == "Value" ? "OrderBy(x => x.Value)" : "OrderByDescending(x => x.Count)";
                    sb.AppendLine($"            .{orderBy}");
                    sb.AppendLine($"            .Take({facet.Limit})");
                }

                sb.AppendLine("            .ToDictionary(x => x.Value, x => x.Count);");
                sb.AppendLine();
            }
            else if (facet.FacetType == "Range")
            {
                sb.AppendLine($"        if (query.Any())");
                sb.AppendLine("        {");
                sb.AppendLine($"            results.{facet.PropertyName}Min = query.Min(x => x.{facet.PropertyName});");
                sb.AppendLine($"            results.{facet.PropertyName}Max = query.Max(x => x.{facet.PropertyName});");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            else if (facet.FacetType == "Boolean")
            {
                sb.AppendLine($"        results.{facet.PropertyName}TrueCount = query.Count(x => x.{facet.PropertyName});");
                sb.AppendLine($"        results.{facet.PropertyName}FalseCount = query.Count(x => !x.{facet.PropertyName});");
                sb.AppendLine();
            }
        }

        sb.AppendLine("        return results;");
        sb.AppendLine("    }");
    }
}
