using Facet.Search.Generators.Models;
using System.Text;

namespace Facet.Search.Generators;

/// <summary>
/// Generates extension methods for applying search filters to IQueryable.
/// </summary>
internal static class ExtensionMethodsGenerator
{
    public static string Generate(SearchableModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Search;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Extension methods for searching {model.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {model.ClassName}SearchExtensions");
        sb.AppendLine("{");

        GenerateApplySearchMethod(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateApplySearchMethod(StringBuilder sb, SearchableModel model)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Applies faceted search filtering to a queryable of {model.ClassName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static System.Linq.IQueryable<{model.Namespace}.{model.ClassName}> ApplyFacetedSearch(");
        sb.AppendLine($"        this System.Linq.IQueryable<{model.Namespace}.{model.ClassName}> query,");
        sb.AppendLine($"        {model.FilterClassName} filter)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (filter == null)");
        sb.AppendLine("            return query;");
        sb.AppendLine();

        foreach (var facet in model.Facets)
            GenerateFacetFilter(sb, facet);

        if (!model.FullTextProperties.IsEmpty)
        {
            sb.AppendLine("        if (!string.IsNullOrWhiteSpace(filter.SearchText))");
            sb.AppendLine("        {");
            sb.AppendLine("            var searchTerm = filter.SearchText.ToLower();");
            sb.Append("            query = query.Where(x => ");

            var first = true;
            foreach (var p in model.FullTextProperties)
            {
                if (!first) sb.Append(" || ");
                sb.Append($"(x.{p.Name} != null && x.{p.Name}.ToLower().Contains(searchTerm))");
                first = false;
            }

            sb.AppendLine(");");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        return query;");
        sb.AppendLine("    }");
    }

    private static void GenerateFacetFilter(StringBuilder sb, SearchFacetInfo facet)
    {
        switch (facet.FacetType)
        {
            case "Categorical":
            case "Hierarchical":
                sb.AppendLine($"        if (filter.{facet.PropertyName}?.Any() == true)");
                sb.AppendLine($"            query = query.Where(x => filter.{facet.PropertyName}.Contains(x.{facet.PropertyName}));");
                break;
            case "Range":
                sb.AppendLine($"        if (filter.Min{facet.PropertyName}.HasValue)");
                sb.AppendLine($"            query = query.Where(x => x.{facet.PropertyName} >= filter.Min{facet.PropertyName}.Value);");
                sb.AppendLine($"        if (filter.Max{facet.PropertyName}.HasValue)");
                sb.AppendLine($"            query = query.Where(x => x.{facet.PropertyName} <= filter.Max{facet.PropertyName}.Value);");
                break;
            case "Boolean":
                sb.AppendLine($"        if (filter.{facet.PropertyName}.HasValue)");
                sb.AppendLine($"            query = query.Where(x => x.{facet.PropertyName} == filter.{facet.PropertyName}.Value);");
                break;
            case "DateRange":
                sb.AppendLine($"        if (filter.{facet.PropertyName}From.HasValue)");
                sb.AppendLine($"            query = query.Where(x => x.{facet.PropertyName} >= filter.{facet.PropertyName}From.Value);");
                sb.AppendLine($"        if (filter.{facet.PropertyName}To.HasValue)");
                sb.AppendLine($"            query = query.Where(x => x.{facet.PropertyName} <= filter.{facet.PropertyName}To.Value);");
                break;
        }
        sb.AppendLine();
    }
}
