using Facet.Search.Generators.Models;
using System.Text;

namespace Facet.Search.Generators;

internal static class FilterClassGenerator
{
    public static string Generate(SearchableModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Search;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated search filter for {model.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class {model.FilterClassName}");
        sb.AppendLine("{");

        foreach (var facet in model.Facets)
            GenerateFacetProperty(sb, facet);

        if (model.FullTextProperties.Length > 0)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Full-text search query.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public string? SearchText { get; set; }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateFacetProperty(StringBuilder sb, SearchFacetInfo facet)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Filter by {facet.DisplayName ?? facet.PropertyName}.");
        sb.AppendLine("    /// </summary>");

        switch (facet.FacetType)
        {
            case "Range":
                sb.AppendLine($"    public {facet.PropertyType}? Min{facet.PropertyName} {{ get; set; }}");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// Maximum {facet.PropertyName} value.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public {facet.PropertyType}? Max{facet.PropertyName} {{ get; set; }}");
                break;
            case "DateRange":
                sb.AppendLine($"    public System.DateTime? {facet.PropertyName}From {{ get; set; }}");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// End date for {facet.PropertyName} filter.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public System.DateTime? {facet.PropertyName}To {{ get; set; }}");
                break;
            case "Geo":
                sb.AppendLine($"    public double? {facet.PropertyName}Latitude {{ get; set; }}");
                sb.AppendLine($"    public double? {facet.PropertyName}Longitude {{ get; set; }}");
                sb.AppendLine($"    public double? {facet.PropertyName}RadiusKm {{ get; set; }}");
                break;
            case "Categorical":
            case "Hierarchical":
                sb.AppendLine($"    public string[]? {facet.PropertyName} {{ get; set; }}");
                break;
            case "Boolean":
                sb.AppendLine($"    public bool? {facet.PropertyName} {{ get; set; }}");
                break;
            default:
                sb.AppendLine($"    public {facet.PropertyType}? {facet.PropertyName} {{ get; set; }}");
                break;
        }
        sb.AppendLine();
    }
}
