using Facet.Search.Generators.Models;
using System.Text;

namespace Facet.Search.Generators;

/// <summary>
/// Generates metadata about searchable facets for frontend consumption.
/// </summary>
internal static class MetadataGenerator
{
    public static string Generate(SearchableModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Search;");
        sb.AppendLine();

        // Generate FacetMetadata class with unique name per model to avoid conflicts
        var metadataClassName = $"{model.ClassName}FacetMetadata";

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Facet metadata for {model.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public class {metadataClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    public string Name { get; set; } = null!;");
        sb.AppendLine("    public string PropertyName { get; set; } = null!;");
        sb.AppendLine("    public string DisplayName { get; set; } = null!;");
        sb.AppendLine("    public string Type { get; set; } = null!;");
        sb.AppendLine("    public bool IsHierarchical { get; set; }");
        sb.AppendLine("    public string? DependsOn { get; set; }");
        sb.AppendLine("    public string OrderBy { get; set; } = null!;");
        sb.AppendLine("    public int Limit { get; set; }");
        sb.AppendLine("    public string? RangeIntervals { get; set; }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Metadata about searchable facets for {model.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {model.ClassName}SearchMetadata");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IReadOnlyList<{metadataClassName}> Facets {{ get; }} = new[]");
        sb.AppendLine("    {");

        foreach (var facet in model.Facets)
        {
            sb.AppendLine($"        new {metadataClassName}");
            sb.AppendLine("        {");
            sb.AppendLine($"            Name = \"{facet.PropertyName}\",");
            sb.AppendLine($"            PropertyName = \"{facet.PropertyName}\",");
            sb.AppendLine($"            DisplayName = \"{facet.DisplayName ?? facet.PropertyName}\",");
            sb.AppendLine($"            Type = \"{facet.FacetType}\",");
            sb.AppendLine($"            IsHierarchical = {facet.IsHierarchical.ToString().ToLower()},");
            sb.AppendLine($"            OrderBy = \"{facet.OrderBy}\",");
            sb.AppendLine($"            Limit = {facet.Limit},");
            if (!string.IsNullOrEmpty(facet.DependsOn))
                sb.AppendLine($"            DependsOn = \"{facet.DependsOn}\",");
            if (!string.IsNullOrEmpty(facet.RangeIntervals))
                sb.AppendLine($"            RangeIntervals = \"{facet.RangeIntervals}\",");
            sb.AppendLine("        },");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
