using Facet.Search.Generators.Models;
using System.Text;

namespace Facet.Search.Generators;

/// <summary>
/// Generates metadata about searchable facets for frontend consumption.
/// </summary>
internal static class MetadataGenerator
{
    public static string Generate(SearchableModel model)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Search;");
        sb.AppendLine();

        // Metadata class
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Metadata about searchable facets for {model.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {model.ClassName}SearchMetadata");
        sb.AppendLine("{");

        // Generate facet metadata
        sb.AppendLine("    public static IReadOnlyList<FacetMetadata> Facets { get; } = new[]");
        sb.AppendLine("    {");

        foreach (var facet in model.Facets)
        {
            sb.AppendLine("        new FacetMetadata");
            sb.AppendLine("        {");
            sb.AppendLine($"            Name = \"{facet.PropertyName}\",");
            sb.AppendLine($"            DisplayName = \"{facet.DisplayName ?? facet.PropertyName}\",");
            sb.AppendLine($"            Type = \"{facet.FacetType}\",");
            sb.AppendLine($"            IsHierarchical = {facet.IsHierarchical.ToString().ToLower()},");

            if (!string.IsNullOrEmpty(facet.DependsOn))
            {
                sb.AppendLine($"            DependsOn = \"{facet.DependsOn}\",");
            }

            sb.AppendLine("        },");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();

        // Metadata model
        sb.AppendLine("public class FacetMetadata");
        sb.AppendLine("{");
        sb.AppendLine("    public string Name { get; set; } = null!;");
        sb.AppendLine("    public string DisplayName { get; set; } = null!;");
        sb.AppendLine("    public string Type { get; set; } = null!;");
        sb.AppendLine("    public bool IsHierarchical { get; set; }");
        sb.AppendLine("    public string? DependsOn { get; set; }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
